### ISSUE TITLE
persistence/player/position

### ISSUE THREAD

**Issue by mrgwilliam** [1st-rapid-response-force/Fusion#1]
I have updated the new position module.

For reference purposes the framework will use the following server code
- 0 - Public Server
- 1 - Framework / Deployment
- 2 - Training Server

What method is this expected?

**Comment by AJCStriker** [comment]
Player Save Position has the following function header: 

save_position ( server_id, player_id, position[x, y, z] )

where:

**server_id** is the ID of the server returned from the register_server command
**player_id** is the GUID of the player whose position is being stored
**position** is an array of x, y, z form containing the vectorized position of the unit.

**Comment by AJCStriker** [comment]
Player Restore Position has the following function header:

restore_position( server_id, player_id )

where:

**server_id** is the id of the server returned from register_server
**player_id** is the GUID of the player being persisted
