### ISSUE TITLE
Inventory returning using JSON style {} instead of []

### ISSUE THREAD

**Issue by mrgwilliam** [1st-rapid-response-force/Fusion#11]
{"","","TRYK_U_B_ARO1_BLK_CombatUniform",{},"",{},"",{},"",{"","","",""},{},"",{"","","",""},{},"",{"","","",""},{},{"ItemMap","ItemCompass","tf_microdagr","tf_anprc152_1"},"",""}

Needs to be stored as ->

["","","TRYK_U_B_ARO1_BLK_CombatUniform",[],"",[],"",[],"",["","","",""],[],"",["","","",""],[],"",["","","",""],[],["ItemMap","ItemCompass","tf_microdagr","tf_anprc152_1"],"",""]

I confirmed that this works by inputting that manually into the database and then recovering, worked like a charm, however the default save is messing up the []

**Comment by AJCStriker** [comment]
The issue is the curly brackets are not JSON. That entire block is invalid
JSON.

I need to know more about what you are actually sending out. If possible
send an array instead of a string so I can directly serialise it.

**Comment by mrgwilliam** [comment]
["","","TRYK_U_B_ARO1_BLK_CombatUniform",[],"",[],"",[],"",["","","",""],[],"",["","","",""],[],"",["","","",""],[],["ItemMap","ItemCompass","tf_microdagr","tf_anprc152_1"],"",""] gets sent to the server, for some reason it turns it into curly brackets

When the command runs it simply grabs the curly braces instead of the correct [] braces

**Comment by AJCStriker** [comment]
I can stringify it or store it as JSON. 

I'll probably just stringify it.
