### ISSUE TITLE
persistence/player/loadout

### ISSUE THREAD

**Issue by mrgwilliam** [1st-rapid-response-force/Fusion#2]
Current Function:

```
_method = "SAVE_PLAYER_INVENTORY";
_params = [_uuid, _loadout];
_response = [_method, _params] call sock_rpc;
```

**Comment by AJCStriker** [comment]
The player inventory persistence function has the header:

save_inventory( server_id, player_id, inventory_string )

where

**server_id** is the id of the server returned from register_server
**player_id** is the GUID of the player being persisted
**inventory_string** is the string representing the persistence value of the player

**Comment by AJCStriker** [comment]
The player inventory restore function has the header:

restore_inventory(server_id, player_id)

where 

**server_id** is the id of the server returned from register_server
**player_id** is the GUID of the player being persisted
